package liquibase

import (
	"fmt"
	"strings"
)

// silentTypes are change types that cannot cause the lock risks DB Guard checks,
// or that DB Guard handles elsewhere; they are not reported as "not analyzed".
var silentTypes = map[string]bool{
	"comment": true, "preConditions": true, "rollback": true, "validCheckSum": true,
	"tagDatabase": true, "dropNotNullConstraint": true, "addDefaultValue": true,
	"dropDefaultValue": true, "renameColumn": true, "renameTable": true,
	"createView": true, "dropView": true, "renameView": true, "createSequence": true,
	"dropSequence": true, "renameSequence": true, "setTableRemarks": true,
	"setColumnRemarks": true, "dropTable": true, "dropIndex": true,
	"dropForeignKeyConstraint": true, "dropUniqueConstraint": true, "dropPrimaryKey": true,
	"insert": true, "update": true, "delete": true, "loadData": true, "loadUpdateData": true,
	"output": true, "stop": true, "empty": true, "executeCommand": true,
	"createProcedure": true, "dropProcedure": true, "dropAllForeignKeyConstraints": true,
}

func translateChangeset(n *node, dir string) Changeset {
	cs := Changeset{ID: n.attr("id"), Author: n.attr("author"), Line: n.line}
	cs.Comment = strings.TrimSpace(n.attr("comment"))
	if c := n.child("comment"); c != nil && cs.Comment == "" {
		cs.Comment = trimText(c.text)
	}
	for _, ch := range n.kids {
		if ch.name == "comment" || ch.name == "rollback" || ch.name == "preConditions" {
			continue
		}
		if !dbmsMatches(ch.attr("dbms")) {
			continue
		}
		stmts, err := translateChange(ch, dir)
		switch {
		case err != nil:
			cs.Problems = append(cs.Problems, err.Error())
		case stmts == nil && !silentTypes[ch.name] && !handled[ch.name]:
			cs.Skipped = append(cs.Skipped, ch.name)
		default:
			cs.SQL = append(cs.SQL, stmts...)
		}
	}
	return cs
}

// handled lists change types translateChange understands (even when they emit nothing).
var handled = map[string]bool{
	"createTable": true, "addColumn": true, "dropColumn": true, "modifyDataType": true,
	"addNotNullConstraint": true, "addUniqueConstraint": true, "addPrimaryKey": true,
	"addForeignKeyConstraint": true, "createIndex": true, "sql": true, "sqlFile": true,
	"addLookupTable": true,
}

// translateChange returns the PostgreSQL statements for one change, or nil if
// the change type is not translated.
func translateChange(ch *node, dir string) ([]string, error) {
	t := tableRef(ch.attr("schemaName"), ch.attr("tableName"))
	switch ch.name {
	case "createTable":
		var cols []string
		for _, c := range ch.children("column") {
			def := q(c.attr("name")) + " " + typeOf(c)
			if strings.EqualFold(constraintAttr(c, "nullable"), "false") {
				def += " NOT NULL"
			}
			cols = append(cols, def)
		}
		if len(cols) == 0 {
			return nil, nil
		}
		return []string{fmt.Sprintf("CREATE TABLE %s (%s)", t, strings.Join(cols, ", "))}, nil

	case "addColumn":
		var out []string
		for _, c := range ch.children("column") {
			s := fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s", t, q(c.attr("name")), typeOf(c))
			if isTrue(c.attr("autoIncrement")) {
				s += " GENERATED BY DEFAULT AS IDENTITY"
			} else if d := defaultExpr(c); d != "" {
				s += " DEFAULT " + d
			}
			if strings.EqualFold(constraintAttr(c, "nullable"), "false") {
				s += " NOT NULL"
			}
			out = append(out, s)
		}
		return out, nil

	case "dropColumn":
		var out []string
		if name := ch.attr("columnName"); name != "" {
			out = append(out, fmt.Sprintf("ALTER TABLE %s DROP COLUMN %s", t, q(name)))
		}
		for _, c := range ch.children("column") {
			out = append(out, fmt.Sprintf("ALTER TABLE %s DROP COLUMN %s", t, q(c.attr("name"))))
		}
		return out, nil

	case "modifyDataType":
		return []string{fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s TYPE %s", t, q(ch.attr("columnName")), ch.attr("newDataType"))}, nil

	case "addNotNullConstraint":
		return []string{fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET NOT NULL", t, q(ch.attr("columnName")))}, nil

	case "addUniqueConstraint", "addPrimaryKey":
		kind := "UNIQUE"
		if ch.name == "addPrimaryKey" {
			kind = "PRIMARY KEY"
		}
		name := ""
		if n := ch.attr("constraintName"); n != "" {
			name = "CONSTRAINT " + q(n) + " "
		}
		if idx := ch.attr("forIndexName"); idx != "" {
			return []string{fmt.Sprintf("ALTER TABLE %s ADD %s%s USING INDEX %s", t, name, kind, q(idx))}, nil
		}
		return []string{fmt.Sprintf("ALTER TABLE %s ADD %s%s (%s)", t, name, kind, colList(ch.attr("columnNames")))}, nil

	case "addForeignKeyConstraint":
		base := tableRef(ch.attr("baseTableSchemaName"), ch.attr("baseTableName"))
		ref := tableRef(ch.attr("referencedTableSchemaName"), ch.attr("referencedTableName"))
		name := ""
		if n := ch.attr("constraintName"); n != "" {
			name = "CONSTRAINT " + q(n) + " "
		}
		s := fmt.Sprintf("ALTER TABLE %s ADD %sFOREIGN KEY (%s) REFERENCES %s (%s)", base, name,
			colList(ch.attr("baseColumnNames")), ref, colList(ch.attr("referencedColumnNames")))
		if v := ch.attr("validate"); v != "" && !isTrue(v) { // Liquibase: validate=false emits NOT VALID on PostgreSQL
			s += " NOT VALID"
		}
		return []string{s}, nil

	case "createIndex":
		var cols []string
		for _, c := range ch.children("column") {
			cols = append(cols, q(c.attr("name")))
		}
		unique := ""
		if isTrue(ch.attr("unique")) {
			unique = "UNIQUE "
		}
		name := ""
		if n := ch.attr("indexName"); n != "" {
			name = q(n) + " "
		}
		return []string{fmt.Sprintf("CREATE %sINDEX %sON %s (%s)", unique, name, t, strings.Join(cols, ", "))}, nil

	case "addLookupTable":
		// Liquibase builds the lookup table from the distinct values, then adds a
		// foreign key on the existing table (validated: it scans that table).
		existing := tableRef(ch.attr("existingTableSchemaName"), ch.attr("existingTableName"))
		lookup := tableRef(ch.attr("newTableSchemaName"), ch.attr("newTableName"))
		col, newCol := ch.attr("existingColumnName"), ch.attr("newColumnName")
		fk := ch.attr("constraintName")
		if fk == "" {
			fk = "FK_" + strings.ToUpper(ch.attr("existingTableName")) + "_" + strings.ToUpper(ch.attr("newTableName"))
		}
		return []string{
			fmt.Sprintf("CREATE TABLE %s AS SELECT DISTINCT %s AS %s FROM %s WHERE %s IS NOT NULL", lookup, q(col), q(newCol), existing, q(col)),
			fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET NOT NULL", lookup, q(newCol)),
			fmt.Sprintf("ALTER TABLE %s ADD PRIMARY KEY (%s)", lookup, q(newCol)),
			fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)", existing, q(fk), q(col), lookup, q(newCol)),
		}, nil

	case "sql":
		text := strings.TrimSpace(ch.text)
		if text == "" {
			text = strings.TrimSpace(ch.attr("sql"))
		}
		if text == "" {
			return nil, nil
		}
		return []string{text}, nil

	case "sqlFile":
		text, err := readSQLFile(dir, ch)
		if err != nil {
			return nil, err
		}
		return []string{strings.TrimSpace(text)}, nil
	}
	return nil, nil
}

func typeOf(c *node) string {
	if t := strings.TrimSpace(c.attr("type")); t != "" {
		return t
	}
	return "text"
}
